name: CI
on:
  push:
    branches: [ main, test ]

jobs:
  prod-build:
    name: Build Docker container for production
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
      - name: Log in to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create secret files
        id: secret-files
        run: |
          echo "${{ secrets.AUTH_JSON_SECRET_FILE }}" | base64 -di > auth.json
          echo "${{ secrets.DOT_ENV_SECRET_FILE }}" | base64 -di > .env
          echo "${{ secrets.SITE_PHP_SECRET_FILE }}" | base64 -di > site.php
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: rodsan0/capstone-ss23:latest
