name: CI
on:
  push:
    branches: [ main, docker-cd-setup ]

jobs:
  prod-build:
    name: build production container
    runs-on: ubuntu-latest
    steps:
      - name: cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
      - name: Log in to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: check out repo
        uses: actions/checkout@v3
      - name: create secret files
        id: secret-files
        run: |
          echo "${{ secrets.AUTH_JSON_SECRET_FILE }}" | base64 -di > ${{ github.workspace }}/auth.json
          echo "${{ secrets.DOT_ENV_SECRET_FILE }}" | base64 -di > ${{ github.workspace }}/.env
          echo "${{ secrets.SITE_PHP_SECRET_FILE }}" | base64 -di > ${{ github.workspace }}/site.php
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}
          push: true
          tags: rodsan0/capstone-ss23:latest
          build-args: --progress=plain
